### ISSUE TITLE
Error importing file

### ISSUE THREAD

**Issue by taylus** [CTurt/GameBoy_GhidraSleigh#6]
Hey, cool project!

I get an error trying to use it though, not sure if I'm doing something wrong.

Created new project -> File -> Import File -> pick any GB rom, get error below:

```
Error importing file: Tetris.gb
ghidra.program.model.lang.CompilerSpecNotFoundException: Exception reading GameBoy:LE:16:default/default(GameBoy.cspec): unexpected attribute "baseinsize"
	at ghidra.program.model.lang.BasicCompilerSpec.<init>(BasicCompilerSpec.java:145)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.getCompilerSpecByID(SleighLanguage.java:1093)
	at ghidra.app.util.opinion.BinaryLoader.loadProgram(BinaryLoader.java:276)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.sun.msv.verifier.ValidityViolation; lineNumber: 12; columnNumber: 91; unexpected attribute "baseinsize"
	at com.sun.msv.verifier.Verifier.onError(Verifier.java:367)
	at com.sun.msv.verifier.Verifier.onError(Verifier.java:363)
	at com.sun.msv.verifier.Verifier.feedAttribute(Verifier.java:294)
	at com.sun.msv.verifier.Verifier.startElement(Verifier.java:221)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at org.iso_relax.verifier.impl.VerifierImpl.verify(VerifierImpl.java:121)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageValidator.validateSleighFile(SleighLanguageValidator.java:103)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageValidator.validateCspecFile(SleighLanguageValidator.java:81)
	at ghidra.program.model.lang.BasicCompilerSpec.<init>(BasicCompilerSpec.java:109)
	... 11 more

---------------------------------------------------
Build Date: 2019-Dec-18 1306 EST
Ghidra Version: 9.1.1
Java Home: D:\Program Files\Amazon Corretto\jdk11.0.6_10
JVM Version: Amazon.com Inc. 11.0.6
OS: Windows 7 6.1 amd64
```

**Comment by taylus** [comment]
I think the `"baseinsize"` attribute it's referring to is in [this part of GameBoy.cspec](https://github.com/CTurt/GameBoy_GhidraSleigh/blob/f9fe5811af3b87c3ef74d4ce1f64498f7c2c36ba/GameBoy/data/languages/GameBoy.cspec#L12). I compared it to the one in [Ghidra's included `z80.cspec`](https://github.com/NationalSecurityAgency/ghidra/blob/0914d476eff65be629d75e61567022db7f21eb6d/Ghidra/Processors/Z80/data/languages/z80.cspec#L12) and see the [format changed on Aug 29](https://github.com/NationalSecurityAgency/ghidra/commit/11d7420af55bfe10c4c448c4284c7280aa53e46d#diff-40405c2a98675d0db7e0c937b8f2b957). Copying that over got it working.

I'm not sure if this is the appropriate thing to do, but I can make a PR if you'd like: https://github.com/CTurt/GameBoy_GhidraSleigh/compare/master...taylus:master
